// <auto-generated />
using DotnetCoreNLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotnetCoreNLayer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210109115220_Person configuration fixed.")]
    partial class Personconfigurationfixed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DotnetCoreNLayer.Core.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            Name = "Pen"
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("DotnetCoreNLayer.Core.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("DotnetCoreNLayer.Core.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("InnerBarcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            IsDeleted = false,
                            Name = "Pen",
                            Price = 12m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1L,
                            IsDeleted = false,
                            Name = "Pencil",
                            Price = 20.50m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 1L,
                            IsDeleted = false,
                            Name = "Marker",
                            Price = 25.40m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 2L,
                            IsDeleted = false,
                            Name = "Small Size Notebook",
                            Price = 50.50m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 2L,
                            IsDeleted = false,
                            Name = "Medium Size Notebook",
                            Price = 60.40m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 2L,
                            IsDeleted = false,
                            Name = "Big Size Notebook",
                            Price = 70.90m,
                            Stock = 80
                        });
                });

            modelBuilder.Entity("DotnetCoreNLayer.Core.Models.Product", b =>
                {
                    b.HasOne("DotnetCoreNLayer.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DotnetCoreNLayer.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
